local_backend: false

backend:
  name: github
  repo: sablelabs-de/blog-content
  branch: main
  base_url: https://decap.sablelabs.de
  auth_endpoint: /auth
  commit_messages:
    create: 'docs(blog): create {{collection}} "{{slug}}"'
    update: 'docs(blog): update {{collection}} "{{slug}}"'
    delete: 'docs(blog): remove {{collection}} "{{slug}}"'
    uploadMedia: "docs(blog): upload {{path}}"
    deleteMedia: "docs(blog): delete {{path}}"
    openAuthoring: "{{message}}"

logo:
  src: /logo-purple.svg
  show_in_header: true

site_url: https://kestrel.chat/
display_url: sablelabs.de

media_folder: drafts/images
public_folder: /uploads

editor:
  preview: false

collections:
  - name: authors
    label: Authors
    folder: src/content/authors
    create: true
    slug: "{{name}}"
    extension: json
    format: json

    fields:
      - { label: Name, name: name, widget: string }
      - { label: Avatar, name: avatar, widget: image, required: false }
      - { label: Role, name: role, widget: string, required: false }

  - name: blog
    label: Blog
    folder: drafts/posts
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"

    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Cover Image, name: image, widget: image, required: false }
      - { label: Image Alt, name: imageAlt, widget: string, required: false }
      - label: Author
        name: author
        widget: relation
        collection: authors
        search_fields: ["name"]
        value_field: name
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Featured, name: featured, widget: boolean, default: false }
      - { label: Draft, name: draft, widget: boolean, default: true }
      - { label: Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown }